language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t jouncato/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jouncato/docker-react npm run test
